### GENERAL SETTINGS ###

# Site settings
title: Seafish Productions
description: "Seafish Productions produces web, mobile, and desktop software."
analytics: "UA-59233374-1"
baseurl: "" #important: start with /
url: "http://seafish.io"

# Build settings
markdown: kramdown
#highlighter: rouge
page_permalink: pretty
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
gems:
  - jekyll-sitemap
  - rouge

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: twitter
    url: https://twitter.com/seandavidfisher
  - title: linkedin
    url: https://www.linkedin.com/in/fishersean
  - title: github
    url: https://github.com/seanfisher

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Provo, UT
    - Silicon Slopes
    - United States
email: inbound@seafish.io
# tel: +34 8493-4893

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Seafish Productions produces web, mobile, and desktop software."
